### ISSUE TITLE
how can test?

### ISSUE THREAD

**Issue by johnfelipe** [christabor/namebot#23]
This is my commands installation in a new ubuntu 14 - 64 bits instance

	sudo apt-get install gcc make build-essential git python-pip python-dev python-setuptools
	git clone https://github.com/christabor/namebot.git
	cd namebot/
	sudo pip install -U setuptools
	sudo pip install -r requirements.txt
	sudo make install

what is next step?

**Comment by christabor** [comment]
Here is an example I whipped up:

```python
# Example usage - this one is slower because it does ALL techniques.
from pprint import pprint as ppr

from namebot import nlp
from namebot import techniques

base_words = ['cat', 'dog']
more_words = nlp.get_synsets(base_words)
all_examples = techniques.generate_all_techniques(base_words)

ppr(all_examples)
```

**Comment by christabor** [comment]
(Reopen if you have any other questions)

**Comment by johnfelipe** [comment]
Hi bro, me again, that snippet code i need create in .py file?
Can you share me commands like i do before:

	sudo nano exmaple.py
	##
	# Example usage - this one is slower because it does ALL techniques.
	from pprint import pprint as ppr

	from namebot import nlp
	from namebot import techniques

	base_words = ['cat', 'dog']
	more_words = nlp.get_synsets(base_words)
	all_examples = techniques.generate_all_techniques(base_words)

	ppr(all_examples)
	##

	python example.py

**Comment by christabor** [comment]
Yep, if you are installing the package system-wide (looks like it based on our `sudo pip install`) then you can create and run the file anywhere. Preferably, I recommend using a https://virtualenv.pypa.io/en/stable/ so your dependencies are isolated to one folder.

e.g. (assuming virtualenv is installed)

```shell
mkdir some_namebot_test ; cd some_namebot_test
virtualenv env
source env/bin/activate
git clone https://github.com/christabor/namebot.git
cd namebot
python setup.py install
touch example.py
# ... assuming you've edited example.py
python example.py
```
